awslabs/stable-diffusion-aws-extension

- infrastructure/src/sd-train/sd-train-deploy-stack.ts
- infrastructure/src/sd-train/train-job-listall-api.ts
- middleware_api/lambda/create_model/train_api.py
- scripts/main.py
> added training job list

- .github/workflows/gh-pages.yml
- README.md
*Issue #, if available:*
*Description of changes:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> [doc] update arch diagram and gh-page workflow

- README.md
*Issue #, if available:*
*Description of changes:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> [doc] README.md for dev enviroment setup

- README.md
- buildspec.yml
- infrastructure/src/main.ts
> Merge dev to main

- README.md
- workshop/ec2.yaml
> doc: add option for the happy pass of webui installation

- README.md
- workshop/ec2.yaml
> Merge main to dev

- docs/middleware-api.yaml
Remove the tokens inside presigned url example in middleware openapi document
> fix: remove tokens inside presigned url example

- build_scripts/build_all.sh
- build_scripts/build_and_push.sh
- build_scripts/source_image_update.sh
- buildspec.yml
- infrastructure/src/common/dockerImageTag.ts
- infrastructure/src/common/dockerImages.ts
- infrastructure/src/main.ts
- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- infrastructure/src/sd-train/model-update-status-api.ts
- infrastructure/src/sd-train/sd-train-deploy-stack.ts
- infrastructure/src/sd-train/train-job-update-api.ts
1. move the reference to ECR image urls into one file.
2. updated the buildspec to build ecr images and updated the inference automatically
> Merge ECR CICD code to dev

- infrastructure/src/common/dockerImages.ts
> fix: remove appending tag

- infrastructure/src/common/dockerImages.ts
> fix: remove unused import

- javascript/txt2img-config.js
> fix: bug fix about controlNet  image get

- javascript/txt2img-config.js
> fix: bug fix about inpaint image get

- README.md
- build_scripts/README.md
- build_scripts/build_and_push.sh
- build_scripts/update_private_ecr.sh
- deployment/build-open-source-dist.sh
- docs/en/architecture-overview/architecture.md
- docs/en/revisions.md
- docs/en/user-guide/CloudAssetsManage.md
- docs/en/user-guide/img2img-guide.md
- docs/en/user-guide/txt2img-guide.md
- docs/zh/user-guide/txt2img-guide.md
- dreambooth_on_cloud/train.py
- pre-flight.sh
- test/api_test/img2img_api_test/img2img_local_api.py
- test/api_test/interrogate_api_test/interrogate_local_api.py
Correct the typo's identified by automatic tool for misspelling. The misspelling identified in './test/api_test/json_files/img2img_inpaint.json:1:' file are not any misspell.
- [X ] This change requires a documentation update, and comments on the code.
> doc update: typo correction

- .github/workflows/pr-validation.yml
- build_scripts/build_all.sh
- docs/middleware-api.yaml
> fix: workflow demo

- scripts/main.py
> feat: remove xlarge from endpoint candidate list

- middleware_api/lambda/inference_result_notification/app.py
Update the DDB status at the end of export image and parametors, otherwise user may find the job completed but the image has not generate error.
> fix: fix can not get inference image and param issue

- aws_extension/sagemaker_ui.py
> fix: fix inference result not show up in dropdown issue

- build_scripts/Dockerfile.inference.from_scratch
> feat: add dockerfile

- aws_extension/sagemaker_ui.py
- scripts/main.py
> Prompt writeback when selecting models

- middleware_api/lambda/inference/parse/parameter_parser.py
> fix: delete extra network prompt adding

- aws_extension/sagemaker_ui.py
- scripts/requirements.txt
> feat: support non-blocking inference with async loop

- pre-flight.bat
windows support for preflight
fixes batch file: preflight
> feat: windows support for preflight

- install.bat
- pre-flight.bat
windows preflight and install file
windows preflight and install file
> feat: windows preflight and install

- aws_extension/sagemaker_ui.py
> fix: add global var to fix non-blocking error

- aws_extension/sagemaker_ui.py
> fix: fix word typo

- buildspec.yml
> fix: rollback original buildspec

- build_scripts/Dockerfile.inference.from_scratch
- [*] Bug fix (non-breaking change which fixes an issue)
> fix: change dockerfile for xformer

- docs/Environment-Preconfiguration.md
- docs/en/deployment/deployment.md
- docs/zh/deployment/deployment.md
Update deployment guide
- [ * ] This change requires a documentation update
> docs: update deployment guide

- build_scripts/training/sagemaker_entrypoint.py
Add force section to mv in sagemaker_entrypoint.py
- [*] Bug fix (non-breaking change which fixes an issue)
> fix: mv bug for dreambooth training

- aws_extension/sagemaker_ui.py
- javascript/txt2img-config.js
- scripts/main.py
> fix: img2img set resizeto as default

- build_scripts/training/sagemaker_entrypoint.py
upload file path part is not right because of a merge conflict not properly resolved
> fix: fixed sagemaker training for lora

- aws_extension/sagemaker_ui.py
> fix: fix lora prompt remove bug

- pre-flight.sh
> fix: remove warning and add user friendly in script

- middleware_api/lambda/inference/parse/parameter_parser.py
> fix: script x/y/z plot with checkpoint name

- javascript/txt2img-config.js
the ui cannot find the right element to get value when inference
> fix: fixed ui element query bug, related to issue

- build_scripts/Dockerfile.inference.from_scratch
> feat: update the inference docker image to install latest xformer lib

- dreambooth_on_cloud/create_model.py
windows fix for assemble a s3 location
> fix: windows s3 path

- aws_extension/sagemaker_ui.py
- scripts/main.py
ui change for new data flow:
- removed all select models field
- add magic button for generate
> feat: ui update for new flow

- aws_extension/sagemaker_ui.py
- scripts/main.py
fix bug for not able to show by selecting from inference id
> fix: comment not used and broken code

- aws_extension/sagemaker_ui.py
- scripts/main.py
allow to display the cloud inference result asynchronously 
> fix: async display cloud infer result

- infrastructure/src/sd-inference/sd-sagemaker-inference-state-machine.ts
> fix: adding missing role for autoscaling

- aws_extension/mme_utils.py
- scripts/main.py
> feat: added vae support

- aws_extension/mme_utils.py
- aws_extension/sagemaker_ui.py
- scripts/main.py
- fixed xyz script when selecting checkpoint names in one of them
- fixed automatic been selected for vae then expose model not found error
- improved our process to ensure the right original process_images_inner method can be load back always
- fixed previous merge conflicts for refreshing endpoint selection
> fix: xyz script fix and other bugs

- docs/zh/developer-guide/api.md
- [ - ] This change requires a documentation update
> doc: update api doc

- docs/en/developer-guide/api.md
- [ - ] This change requires a documentation update
> doc: update api doc in en

- aws_extension/sagemaker_ui.py
- javascript/txt2img-config.js
- scripts/main.py
> feat: fix html style and rollback old upload component

- buildspec.yml
> fix: adding retry for getting github latest tags

- scripts/main.py
> fix: inpaint mask update

- build_scripts/inference/serve
> fix: sdxl inference nan bug.

- javascript/txt2img-config.js
- scripts/main.py
> fix: hidden new upload components

- infrastructure/src/sd-inference/sd-async-inference-stack.ts
added missing permission for deleting endpoint
> fix: fixed permission issue when delete endpoints (issue #161)

- middleware_api/lambda/model_and_train/model_api.py
fixed dreambooth create model to use the proper api request
> fix: fixed create model in model_api.py

- scripts/main.py
dataset view using image gallery still not support the raw s3 url yet, so rollback the previous version and will fix later
> fix: Update main.py for dataset view

- scripts/main.py
> fix: scripts not finding the right one

- scripts/main.py
> fix: script validation when sending request to backend

- middleware_api/lambda/check_endpoint_deployment/app.py
- [*] Bug fix (non-breaking change which fixes an issue)
> update scaling policy

- aws_extension/mme_utils.py
> fix: vae model not load in mme_utils.py

- workshop/ec2.yaml
> fix: Update ec2.yaml for python3.10 and enable ssh key

- infrastructure/src/sd-inference/sd-async-inference-stack.ts
> fix: [release20230913] Update sd-async-inference-stack.ts

- middleware_api/lambda/check_endpoint_deployment/app.py
- [* ] Bug fix (non-breaking change which fixes an issue)
> patch fix: merge autoscaling policy from dev to main

- aws_extension/mme_utils.py
- aws_extension/sagemaker_ui.py
- build_scripts/Dockerfile.inference.from_scratch
- infrastructure/src/main.ts
- infrastructure/src/sd-train/checkpoint-upload-api.ts
- infrastructure/src/sd-train/sd-train-deploy-stack.ts
- javascript/txt2img-config.js
- middleware_api/lambda/inference/app.py
- middleware_api/lambda/inference_result_notification/app.py
- middleware_api/lambda/model_and_train/checkpoint_api.py
- middleware_api/lambda/model_and_train/common_tools.py
- scripts/main.py
> feat: merge dev xiujuan own commit pr to main

- aws_extension/cloud_models_manager/sd_manager.py
- aws_extension/mme_utils.py
> feat: fix lora name bug, and generate on cloud not change error

- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- update_scripts/delete_resource.sh
Fix multi-user issue and add delete resource script
- [ - ] Bug fix (non-breaking change which fixes an issue)
> fix: fix multi-user issue and add delete resource script

- install.sh
> fix: typo in install.sh

- install.sh
> fix: Update install.sh

- workshop/ec2.yaml
> fix: 3.10 conflicts fix

- aws_extension/mme_utils.py
- aws_extension/sagemaker_ui.py
- middleware_api/lambda/inference_v2/inference_api.py
- scripts/main.py
vae is a common variable in original ui. Added a new field to select vae
> fix: fixed vae for multi users

- dreambooth_on_cloud/ui.py
- infrastructure/src/sd-train/checkpoint-upload-api.ts
- middleware_api/lambda/model_and_train/checkpoint_api.py
> fix: optimize memory usage for model upload requests

- aws_extension/sagemaker_ui.py
- scripts/main.py
when inference, check model from cloud not from local
> fix: lora model loads from cloud

- infrastructure/src/main.ts
- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- infrastructure/src/sd-inference/sd-sagemaker-inference-state-machine.ts
- infrastructure/src/shared/deploy-role.ts
- Fixed create/find `LambdaStartDeployRole` resource.
- Improved stack design.
> fix: created/find LambdaStartDeployRole logic

- README.md
- docs/en/deployment/deployment.md
- docs/en/deployment/deployment_for_existing_users.md
- docs/en/troubleshooting.md
- docs/en/user-guide/dreambooth-guide.md
- docs/en/user-guide/img2img-guide.md
- docs/en/user-guide/txt2img-guide.md
- docs/zh/deployment/template.md
- docs/zh/user-guide/controlnet-guide.md
- docs/zh/user-guide/img2img-guide.md
- docs/zh/user-guide/txt2img-guide.md
> fix: Fixed some typos

- scripts/main.py
> feat: fix default controlnet model count

- middleware_api/lambda/check_endpoint_deployment/app.py
- Optimized the auto-scaling policy to improve user experience.
> fix: improved SageMaker autoscaling policy

- aws_extension/cloud_api_manager/api_manager.py
- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
- middleware_api/lambda/requirements.txt
- Hidden deleted endpoint in delete endpoint list.
> fix: hidden deleted endpoint

- aws_extension/inference_scripts_helper/controlnet_helper.py
- aws_extension/inference_scripts_helper/refiner_helper.py
- aws_extension/inference_scripts_helper/scripts_processor.py
- aws_extension/inference_scripts_helper/xyz_helper.py
- scripts/main.py
hotfix for release 1.2.1: controlnet problem
> fix: controlnet cannot get selected (#252)

- aws_extension/cloud_api_manager/api_manager.py
- infrastructure/src/sd-inference/sagemaker-endpoints-delete.ts
- infrastructure/src/sd-inference/sagemaker-endpoints-event.ts
- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- middleware_api/lambda/check_endpoint_deployment/app.py
- middleware_api/lambda/inference/app.py
- middleware_api/lambda/inference_v2/_enums.py
- middleware_api/lambda/inference_v2/_types.py
- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
- middleware_api/lambda/inference_v2/sagemaker_endpoint_events.py
- middleware_api/lambda/requirements.txt
- Using Lambda Runtime instead of Docker Image.
- Fixed Endpoint status loss or out of sync issues.
- Decouple message notifications using EventBridge.
- Use `aws_lambda_powertools`.
- Release new RESTful API for `DELETE` endpoints.
- Validate input parameters using API Gateway Model.
- Formatted changed files.
> feat: Improved endpoint design

- aws_extension/sagemaker_ui.py
cloud vae list not load properly 
> fix: vae loading without checking ui settings

- aws_extension/sagemaker_ui.py
> fix: vae load without setup sd_vae

- aws_extension/auth_service/simple_cloud_auth.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- utils.py
> feat: fix strip

- docs/en/developer-guide/api.md
- docs/middleware-api.yaml
- docs/zh/developer-guide/api.md
- middleware_api/lambda/inference_v2/_types.py
- middleware_api/lambda/multi_users/multi_users_api.py
- scripts/main.py
- Updated api docs
- Fixed typos
> feat: Update api docs

- aws_extension/sagemaker_ui_tab.py
- fixed endpoint instance type duplication
> fix: endpoint instance type duplication

- scripts/api.py
sagemaker will hang and get no response if json payload from s3 is failed to parse
> fix: fixed sagemaker endpoint dead lock bug

- middleware_api/lambda/multi_users/multi_users_api.py
- scripts/api.py
> fix: merge conflicts

- aws_extension/mme_utils.py
- middleware_api/lambda/multi_users/multi_users_api.py
- scripts/api.py
> fix: embeddings model is downloaded to the wrong location

- scripts/main.py
> feat: fix the error in inference due to replacing the source scripts in XYZ

- infrastructure/src/sd-inference/sagemaker-endpoints-event.ts
- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
- Improved sagemaker endpoint event handler
> feat: Improved sagemaker endpoint event handler

- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
- Improved sagemaker endpoint event handler
> fix: improved sagemaker endpoint event handler

- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
- fix allow endpoint name is empty
> fix:  allow endpoint name is empty

- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
> fix: create endpoint check

- middleware_api/lambda/model_and_train/train_api.py
- Fixed model item exists check condition
> fix: model item exists check condition

- aws_extension/auth_service/simple_cloud_auth.py
- aws_extension/cloud_api_manager/api_manager.py
- infrastructure/src/api/checkpoints/delete-checkpoints.ts
- infrastructure/src/api/datasets/delete-datasets.ts
- infrastructure/src/api/inferences/delete-inference-jobs.ts
- infrastructure/src/api/models/delete-models.ts
- infrastructure/src/api/roles/delete-roles.ts
- infrastructure/src/api/trainings/delete-training-jobs.ts
- infrastructure/src/sd-inference/sagemaker-endpoints-delete.ts
- infrastructure/src/sd-users/multi-users-stack.ts
- infrastructure/src/sd-users/role-upsert-api.ts
- infrastructure/src/sd-users/roles-listall-api.ts
- infrastructure/src/sd-users/user-delete-api.ts
- infrastructure/src/sd-users/users-listall-api.ts
- infrastructure/src/shared/rest-api-gateway.ts
- middleware_api/lambda/common/response.py
- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
- middleware_api/lambda/multi_users/multi_users_api.py
- middleware_api/lambda/multi_users/roles_api.py
- Improved delete endpoints api
- Improved delete users api
> feat: improved delete endpoints/roles/users api

- aws_extension/cloud_api_manager/api_manager.py
- infrastructure/src/sd-train/chekpoints-listall-api.ts
- infrastructure/src/sd-train/sd-train-deploy-stack.ts
- middleware_api/lambda/common/response.py
- middleware_api/lambda/model_and_train/checkpoint_api.py
> feat: update list checkpoints api

- aws_extension/cloud_api_manager/api_manager.py
- dreambooth_on_cloud/train.py
- infrastructure/src/sd-inference/sagemaker-endpoints-listall.ts
- infrastructure/src/sd-inference/sagemaker-inference-listall.ts
- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- infrastructure/src/sd-train/datasets-listall-api.ts
- infrastructure/src/sd-train/model-job-listall-api.ts
- infrastructure/src/sd-train/sd-train-deploy-stack.ts
- infrastructure/src/sd-train/train-job-listall-api.ts
- middleware_api/lambda/common/response.py
- middleware_api/lambda/dataset_service/dataset_api.py
- middleware_api/lambda/inference_v2/inference_api.py
- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
- middleware_api/lambda/model_and_train/model_api.py
- middleware_api/lambda/model_and_train/train_api.py
> feat: update list resources api

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/sd-inference/sagemaker-endpoints-create.ts
- infrastructure/src/sd-inference/sagemaker-endpoints-delete.ts
- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- infrastructure/src/sd-train/chekpoint-create-api.ts
- infrastructure/src/sd-train/chekpoint-update-api.ts
- infrastructure/src/sd-train/dataset-create-api.ts
- infrastructure/src/sd-train/dataset-update-api.ts
- infrastructure/src/sd-train/datasets-item-listall-api.ts
- infrastructure/src/sd-train/sd-train-deploy-stack.ts
- infrastructure/src/sd-users/multi-users-stack.ts
- infrastructure/src/sd-users/user-upsert-api.ts
- middleware_api/lambda/dataset_service/dataset_api.py
- middleware_api/lambda/inference_v2/sagemaker_endpoint_api.py
- middleware_api/lambda/model_and_train/checkpoint_api.py
- middleware_api/lambda/multi_users/multi_users_api.py
- Updated checkpoints/endpoints/datasets apis
> feat: update checkpoints/endpoints/datasets apis

- aws_extension/sagemaker_ui_tab.py
> fix: placeholder typos

- aws_extension/sagemaker_ui_tab.py
> feat: hidden endpoint id in list

- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- fix ephemeralStorageSize type error
> fix: Ephemeral storage size tyep error

- aws_extension/sagemaker_ui.py
> fix: select inference job

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui_tab.py
- improved test connection and update settings
> feat: improved update api setting

- aws_extension/cloud_api_manager/api_manager.py
> feat: Cannot delete current user

- aws_extension/sagemaker_ui_tab.py
> feat: improved dataset create

- docs/en/architecture-overview/architecture.md
- docs/en/deployment/deployment.md
- docs/en/deployment/deployment_for_existing_users.md
- docs/en/deployment/template.md
- docs/en/developer-guide/api.md
- docs/en/faq.md
- docs/en/index.md
- docs/en/template.md
- docs/en/uninstall.md
- docs/zh/deployment/deployment_for_existing_users.md
- docs/zh/developer-guide/api.md
> feat: update solution docs

- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/endpoints/create-endpoint.ts
- improved create endpoint instance config
> feat: improved create endpoint

- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/checkpoints/update-chekpoint.ts
- infrastructure/src/api/datasets/create-dataset.ts
- infrastructure/src/api/datasets/get-dataset.ts
- infrastructure/src/api/datasets/update-dataset.ts
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/api/inferences/start-inference-job.ts
- infrastructure/src/api/models/update-model.ts
- infrastructure/src/api/trainings/create-training-job.ts
- infrastructure/src/api/trainings/update-training-job.ts
- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- infrastructure/src/sd-train/create-model-endpoint.ts
- infrastructure/src/shared/sns-topics.ts
> feat: updated partition for arn

- aws_extension/cloud_infer_service/simple_sagemaker_infer.py
- update create inference job status code
> fix: update create inference job status code

- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/checkpoints/create-chekpoint.ts
- middleware_api/lambda/checkpoints/create_checkpoint.py
- middleware_api/lambda/checkpoints/update_checkpoint_by_url.py
> feat: Async url upload

- aws_extension/sagemaker_ui.py
> fix: fixed inference job display

- aws_extension/cloud_api_manager/api_manager.py
- middleware_api/lambda/roles/create_role.py
- middleware_api/lambda/users/create_user.py
> fix: Create user status code

- aws_extension/cloud_api_manager/api.py
- aws_extension/sagemaker_ui.py
- javascript/utils.js
- support delete inference job
> feat: support delete inference job

- aws_extension/sagemaker_ui.py
> feat: Check ckpt upload param

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- javascript/txt2img-config.js
- middleware_api/lambda/checkpoints/create_checkpoint.py
- keep ckpt name unique
- supported delte ckpts
> feat: Ckpt name unique

- aws_extension/cloud_api_manager/api.py
- middleware_api/lambda/common/response.py
> feat: Add api version

- aws_extension/cloud_api_manager/api.py
- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/checkpoints/list-chekpoints.ts
- infrastructure/src/api/checkpoints/update-chekpoint.ts
- infrastructure/src/api/datasets/create-dataset.ts
- infrastructure/src/api/datasets/delete-datasets.ts
- middleware_api/lambda/checkpoints/create_checkpoint.py
- middleware_api/lambda/checkpoints/list_checkpoints.py
- middleware_api/lambda/checkpoints/update_checkpoint.py
- middleware_api/lambda/checkpoints/update_checkpoint_rename.py
- supported ckpts filter
- fixed some bugs
- rename function async
> feat: support ckpts filter

- aws_extension/cloud_api_manager/api.py
- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_utils.py
- middleware_api/lambda/checkpoints/list_checkpoints.py
- middleware_api/lambda/common/response.py
- middleware_api/lambda/common/util.py
- middleware_api/lambda/endpoints/endpoint_event.py
- check api version
- resord lora model seelct
- improved list ckpts api
> feat: check api version

- aws_extension/sagemaker_ui_tab.py
> feat: improved CheckPoint Management

- aws_extension/cloud_api_manager/api.py
> feat: Use 1.3.0 current

- middleware_api/lambda/checkpoints/create_checkpoint.py
- middleware_api/lambda/tests/test_api.py
- support get civitai real link
> feat: support get civitai real link

- infrastructure/package.json
> feat: update cdk version

- aws_extension/sagemaker_ui_utils.py
> feat: Improved warning time

- aws_extension/cloud_api_manager/api_manager.py
- middleware_api/lambda/endpoints/delete_endpoints.py
> feat: allow delete all endpoints

- aws_extension/cloud_api_manager/api.py
- dreambooth_on_cloud/create_model.py
- dreambooth_on_cloud/train.py
- middleware_api/lambda/models/list_models.py
- middleware_api/lambda/trainings/list_training_jobs.py
- fixed model and train api request
> fix: model & train api request

- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/trainings/start-training-job.ts
- middleware_api/lambda/trainings/start_training_job.py
> feat: add user filter group

- aws_extension/cloud_api_manager/api.py
- dreambooth_on_cloud/create_model.py
- dreambooth_on_cloud/train.py
- infrastructure/src/api/trainings/start-training-job.ts
- infrastructure/src/api/trainings/stop-training-job.ts
- infrastructure/src/sd-train/sd-train-deploy-stack.ts
- middleware_api/lambda/checkpoints/create_checkpoint.py
- middleware_api/lambda/libs/enums.py
- middleware_api/lambda/trainings/stop_training_job.py
> feat: supported stop train api

- dreambooth_on_cloud/train.py
> feat: remove unsed params

- middleware_api/lambda/trainings/start_training_job.py
> fix: fix region in lambda

- middleware_api/lambda/trainings/start_training_job.py
> feat: log error in start train

- infrastructure/src/shared/rest-api-gateway.ts
> feat: Update api name

- aws_extension/constant.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_utils.py
Add embedding and hypernetwork selection
The testing for update prompt by multiple user has been passed
- [ - ] New feature (non-breaking change which adds functionality)
> feat: add embedding and hypernetwork selection

- middleware_api/lambda/checkpoints/create_checkpoint.py
- middleware_api/lambda/checkpoints/update_checkpoint.py
- middleware_api/lambda/common/response.py
> feat: allow cors

- middleware_api/lambda/trainings/start_training_job.py
> fix: fixed logger info

- dreambooth_on_cloud/create_model.py
- dreambooth_on_cloud/train.py
> fix: log level

- aws_extension/sagemaker_ui_tab.py
- utils.py
> feat: Improved logout

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- improved api request params check
> feat: improved api request params check

- aws_extension/cloud_api_manager/api.py
- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/cloud_models_manager/sd_manager.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- dreambooth_on_cloud/create_model.py
- dreambooth_on_cloud/train.py
- utils.py
> feat: Improved api call

- middleware_api/lambda/common/schemas/checkpoints.py
- middleware_api/lambda/common/schemas/datasets.py
- middleware_api/lambda/common/schemas/endpoints.py
- middleware_api/lambda/common/schemas/inferences.py
- middleware_api/lambda/common/schemas/models.py
- middleware_api/lambda/common/schemas/roles.py
- middleware_api/lambda/common/schemas/trainings.py
- middleware_api/lambda/common/schemas/users.py
- middleware_api/lambda/requirements.txt
> feat: Added Schemas & Heatoas

- infrastructure/src/shared/resource-provider-on-event.ts
- fixed stack delete invoke lambda error
> fix: stack delete invoke error

- middleware_api/lambda/roles/create_role.py
> freat: Remove no use role return

- middleware_api/lambda/users/create_user.py
- middleware_api/lambda/users/delete_users.py
> Fix: users return

- middleware_api/lambda/endpoints/create_endpoint.py
> fix: Fix res return

- middleware_api/lambda/checkpoints/update_checkpoint.py
> fix: Fix response

- middleware_api/lambda/common/response.py
> feat: use 1.3.0

- infrastructure/src/api/models/update-model.ts
> feat: Update utils name

- aws_extension/sagemaker_ui.py
- docs/en/user-guide/img2img-guide.md
- docs/en/user-guide/txt2img-guide.md
- docs/zh/user-guide/img2img-guide.md
> feat: improved Infer histories

- aws_extension/sagemaker_ui.py
- middleware_api/lambda/endpoints/create_endpoint.py
- middleware_api/lambda/inferences/create_inference_job.py
- middleware_api/lambda/libs/data_types.py
-  added Infer time and instance tyle
> feat: added Infer time and instance tyle

- aws_extension/cloud_api_manager/api_manager.py
- use none when no name in ckpt list
> fix: use none when no name in ckpt list

- infrastructure/src/shared/resource-provider-on-event.ts
> feat: update gcr bucket

- scripts/api.py
- remove error print in endpoint
> fix: Logger in endpoint

- install.sh
- improved shell for install.sh
> feat: Improved shell

- infrastructure/src/api/trainings/delete-training-jobs.ts
- middleware_api/lambda/trainings/delete_training_jobs.py
> feat: Update request model name

- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/shared/resource-provider-on-event.ts
- middleware_api/lambda/inferences/start_inference_job.py
> feat: Improved UI and s3

- install.sh
- workshop/ec2.yaml
> feat: update install.sh

- install.sh
> feat: Update ec2 install

- workshop/ec2.yaml
> feat: Update ec2 deploy

- aws_extension/sagemaker_ui.py
> feat: Update infernec time

- aws_extension/sagemaker_ui.py
> feat: use \n for endpoint info

- aws_extension/sagemaker_ui.py
> fix: fix when params deleted

- aws_extension/sagemaker_ui_tab.py
- utils.py
- only show gcr instance tyoes when api delpoyed gcr
> feat: only show gcr instance tyoes when api delpoyed gcr

- workshop/ec2.yaml
> feat: update ec2 ami

- infrastructure/src/sd-train/create-model-endpoint.ts
> feat: update utils model name

- workshop/ec2.yaml
> feat: update ec2 InstanceType

- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
> feat: Remove serverless

- install.sh
> feat: update extensions install

- middleware_api/lambda/inferences/start_inference_job.py
> feat: Display error in endpoint

- infrastructure/src/api/models/update-model.ts
- infrastructure/src/api/trainings/start-training-job.ts
- infrastructure/src/sd-inference/sd-async-inference-stack.ts
> feat: reanme ecr resource name

- aws_extension/sagemaker_ui_tab.py
> feat: Custom docker image uri

- workshop/ec2.yaml
- Add v1-5 and xl for ec2 deploy file
> feat: Add v1-5 and xl for ec2 deploy file

- build_scripts/inference/serve_start
- print file content in endpoint for debug
> feat: print file content in endpoint for debug

- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/checkpoints/delete-checkpoints.ts
- infrastructure/src/api/checkpoints/update-chekpoint.ts
- infrastructure/src/api/datasets/create-dataset.ts
- infrastructure/src/api/datasets/delete-datasets.ts
- infrastructure/src/api/datasets/update-dataset.ts
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/api/endpoints/delete-endpoints.ts
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/api/inferences/delete-inference-jobs.ts
- infrastructure/src/api/models/create-model.ts
- infrastructure/src/api/models/delete-models.ts
- infrastructure/src/api/models/update-model.ts
- infrastructure/src/api/roles/create-role.ts
- infrastructure/src/api/roles/delete-roles.ts
- infrastructure/src/api/trainings/create-training-job.ts
- infrastructure/src/api/trainings/delete-training-jobs.ts
- infrastructure/src/api/users/create-user.ts
- infrastructure/src/api/users/delete-users.ts
- remove request ValidatorName
> feat: remove request ValidatorName

- infrastructure/src/shared/resource-provider.ts
> feat: Remove actions

- build_scripts/inference/serve_start
- middleware_api/lambda/inferences/result_notification/app.py
> fix: added missing task type

- middleware_api/lambda/inferences/result_notification/app.py
- middleware_api/lambda/inferences/start_inference_job.py
> feat: Improved inference result

- middleware_api/lambda/inferences/start_inference_job.py
> fix: real-time record

- middleware_api/lambda/inferences/start_inference_job.py
> feat: remove-sns-in-real-time

- middleware_api/lambda/libs/enums.py
- add Pending for train status
> ftx: add Pending for train status

- javascript/txt2img-config.js
> fix: upload from local

- infrastructure/src/shared/resource-provider-on-event.ts
- install.sh
> feat: support Sd 1.7.0

- middleware_api/lambda/inferences/result_notification/app.py
- middleware_api/lambda/inferences/start_inference_job.py
> feat: support png

- build_scripts/Dockerfile.inference.from_scratch
> feat: Update docker

- build_scripts/Dockerfile.inference.from_scratch
- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/checkpoints/delete-checkpoints.ts
- infrastructure/src/api/checkpoints/update-chekpoint.ts
- infrastructure/src/api/datasets/create-dataset.ts
- infrastructure/src/api/datasets/delete-datasets.ts
- infrastructure/src/api/datasets/list-datasets.ts
- infrastructure/src/api/datasets/update-dataset.ts
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/api/endpoints/delete-endpoints.ts
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/api/inferences/delete-inference-jobs.ts
- infrastructure/src/api/models/create-model.ts
- infrastructure/src/api/models/delete-models.ts
- infrastructure/src/api/models/update-model.ts
- infrastructure/src/api/roles/create-role.ts
- infrastructure/src/api/roles/delete-roles.ts
- infrastructure/src/api/trainings/create-training-job.ts
- infrastructure/src/api/trainings/delete-training-jobs.ts
- infrastructure/src/api/users/create-user.ts
- infrastructure/src/api/users/delete-users.ts
- infrastructure/src/sd-inference/sd-async-inference-stack.ts
- infrastructure/src/sd-train/sd-train-deploy-stack.ts
> feat: Rename api validator

- build_scripts/build_and_push.sh
- install.sh
> Fix: install sh

- build_scripts/build_and_push.sh
- install.sh
> feat: Update install

- build_scripts/build_all.sh
- build_scripts/build_and_push_inference.sh
- infrastructure/src/common/dockerImages.ts
> fix: Docker build shell

- docs/en/developer-guide/api.md
- docs/middleware.openapi.json
- docs/middleware.openapi.yaml
- docs/zh/developer-guide/api.md
- middleware_api/lambda/inferences/create_inference_job.py
- middleware_api/lambda/inferences/inference_api.py
> feat: update api doc

- aws_extension/cloud_api_manager/api.py
> feat: update client api version

- infrastructure/src/shared/resource-provider-on-event.ts
> fix: missing g5 so

- scripts/main.py
> fix: inference_queue

- middleware_api/lambda/inference/requirements.txt
> fix: update gradio version

- infrastructure/src/events/endpoints-event.ts
> fix: Auto scalling policy

- docs/en/user-guide/multi-user.md
> fix: some typos

- docs/en/cost.md
- docs/en/solution-overview/features-and-benefits.md
Remove Dreambooth from the guidance doc.
> docs: remove dreambooth from doc

- aws_extension/cloud_api_manager/api_logger.py
> fix: mkdir outputs if not exists

- aws_extension/cloud_api_manager/api_logger.py
> feat: use json dumps for copy

- aws_extension/cloud_infer_service/simple_sagemaker_infer.py
- middleware_api/lambda/inferences/create_inference_job.py
> feat: Remove unused parametes

- aws_extension/cloud_infer_service/simple_sagemaker_infer.py
> feat: Improved infer start

- docs/en/developer-guide/api.md
- docs/zh/developer-guide/api.md
> fix: update api doc

- aws_extension/cloud_api_manager/api.html
- aws_extension/cloud_api_manager/api_logger.py
- aws_extension/cloud_infer_service/simple_sagemaker_infer.py
- aws_extension/sagemaker_ui.py
- middleware_api/lambda/inferences/create_inference_job.py
> feat: Added desc

- aws_extension/sagemaker_ui_tab.py
> feat: improved connect tip

- docs/en/cost.md
> feat: Update main doc

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_utils.py
- infrastructure/src/api/inferences/list-inferences.ts
- infrastructure/src/main.ts
- infrastructure/src/shared/resource-provider-on-event.ts
- infrastructure/src/shared/resource-provider.ts
- middleware_api/lambda/common/response.py
- middleware_api/lambda/inferences/list_inferences.py
- middleware_api/lambda/libs/utils.py
- infernecs page patch to main
> fix: infernecs page patch to main

- aws_extension/sagemaker_ui.py
- docs/en/developer-guide/api_debugger.md
- docs/en/user-guide/multi-user.md
- docs/zh/developer-guide/api_debugger.md
> feat: update from main branch

- .gitallowed
- .viperlightignore
> feat: Recovery ignore

- aws_extension/cloud_api_manager/api.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- Compatible with lower versions of APIs without type filters to main
> feat: Compatible with lower versions of APIs without type filters to main

- aws_extension/cloud_api_manager/api.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- Compatible with lower versions of APIs without type filters
> feat: Compatible with lower versions of APIs without type filters

- infrastructure/src/main.ts
- infrastructure/src/shared/resource-provider.ts
- improved resource manager update logic
> feat: Improved resource manager

- infrastructure/src/main.ts
- infrastructure/src/shared/resource-provider.ts
- improved resource manager update logic
> feat: improved resource manager update logic

- aws_extension/auth_service/simple_cloud_auth.py
> feat: improved shared

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/events/endpoints-event.ts
- middleware_api/lambda/endpoints/create_endpoint.py
- middleware_api/lambda/endpoints/endpoint_event.py
- middleware_api/lambda/inferences/create_inference_job.py
- middleware_api/lambda/libs/data_types.py
- improved create endpoint and cool down
> feat: improved create endpoint and cool down

- middleware_api/lambda/endpoints/create_endpoint.py
> feat: improved endpoint config

- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/api/inferences/start-inference-job.ts
- middleware_api/lambda/inferences/create_inference_job.py
- middleware_api/lambda/inferences/get_inference_job.py
- middleware_api/lambda/inferences/inference_libs.py
- middleware_api/lambda/inferences/start_inference_job.py
- middleware_api/lambda/libs/utils.py
- Supported real time inference
> feat: Supported real time inference

- middleware_api/lambda/endpoints/endpoint_event.py
> Support real time inference

- middleware_api/lambda/endpoints/endpoint_event.py
- middleware_api/lambda/libs/data_types.py
- Catch endpoint event exception
> feat: Catch endpoint

- middleware_api/lambda/endpoints/endpoint_event.py
> feat: record deploy seconds

- middleware_api/lambda/endpoints/endpoint_event.py
- middleware_api/lambda/libs/data_types.py
> fix: deploy seconds option

- middleware_api/lambda/users/create_user.py
> fix: user create

- aws_extension/sagemaker_ui_tab.py
- middleware_api/lambda/roles/create_role.py
- middleware_api/lambda/users/create_user.py
> fix: create role for init

- middleware_api/lambda/requirements.txt
> fix: security issues

- middleware_api/lambda/inferences/start_inference_job.py
> feat: Improved infer

- build_scripts/inference/serve_start
- use no webui model in endpoint
> feat: use no webui model in endpoint

- aws_extension/auth_service/simple_cloud_auth.py
> feat: improved auth tip

- infrastructure/src/cdk-ecr-deployment/lambda/Dockerfile
- infrastructure/src/cdk-ecr-deployment/lib/index.ts
> feat: update al2023 runtime

- infrastructure/src/cdk-ecr-deployment/lambda/Dockerfile
- infrastructure/src/cdk-ecr-deployment/lib/index.ts
- updated golang runtime to al2023
> feat: updated golang runtime to al2023

- workshop/custom_502.html
- workshop/ec2.yaml
- workshop/nginx_proxy.conf
- use Nginx proxy for workshop
> feat: use Nginx proxy for workshop

- workshop/ec2.yaml
- workshop/models.txt
> feat: Improved model download

- workshop/ec2.yaml
> feat: added toute table for ec2

- workshop/ec2.yaml
- workshop/models.txt
> feat: improved ec2 yaml

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui_tab.py
- build_scripts/inference/serve_start
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/common/dockerImageTag.ts
- middleware_api/lambda/endpoints/create_endpoint.py
- middleware_api/lambda/libs/data_types.py
- workshop/ec2.yaml
- recovery ecr tag and improved extensions
> feat: recovery ecr tag and improved extensions

- aws_extension/sagemaker_ui_tab.py
- build_scripts/Dockerfile.inference.quick
- build_scripts/inference/serve_start
- middleware_api/lambda/endpoints/create_endpoint.py
- support clone extensions in sagemaker
> feat: support clone extensions in sagemaker

- aws_extension/sagemaker_ui_tab.py
- infrastructure/package.json
- update cdk version for resolve cdk issue
> feat: update cdk version for resolve cdk issue

- workshop/ec2.yaml
> feat: improved ec2 start

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui_tab.py
- middleware_api/lambda/datasets/create_dataset.py
- middleware_api/lambda/datasets/get_dataset.py
- middleware_api/lambda/libs/data_types.py
- supported dataset set prefix
> feat: support dataset set prefix

- infrastructure/src/api/trainings/delete-training-jobs.ts
- infrastructure/src/api/trainings/get-training-job.ts
- infrastructure/src/api/trainings/stop-training-job.ts
- infrastructure/src/shared/train-deploy.ts
- middleware_api/lambda/libs/utils.py
- middleware_api/lambda/trainings/create_training_job.py
- middleware_api/lambda/trainings/get_training_job.py
> fix: train bugs

- aws_extension/sagemaker_ui_tab.py
- workshop/ec2.yaml
> feat: improved ec2 restart logic

- middleware_api/lambda/endpoints/endpoint_event.py
> feat: improved scaling policy

- docs/en/developer-guide/api/1.5.0.md
- docs/zh/developer-guide/api/1.5.0.md
- [ - ] This change requires a documentation update
> docs: update training api

- build_scripts/build_files_in_sagemaker.sh
- build_scripts/build_inference_image.sh
- build_scripts/inference/serve
- infrastructure/src/api/endpoints/create-endpoint.ts
- update permission for get esd files
> feat: update permission for get esd files

- build_scripts/build_files_in_sagemaker.sh
- build_scripts/inference/serve
> deat: improved dlc

- build_scripts/build_files_in_sagemaker.sh
- workshop/ec2.yaml
> feat: improved dlc

- build_scripts/build_files_in_sagemaker.sh
- build_scripts/inference/serve
- scripts/requirements.txt
> feat: added markdown

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/cloud_dataset_manager/dataset_manager.py
- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
- build_scripts/inference/serve.sh
- middleware_api/lambda/checkpoints/update_checkpoint_by_url.py
- middleware_api/lambda/datasets/list_datasets.py
- middleware_api/lambda/libs/utils.py
> feat: Improved permission

- build_scripts/inference/serve.sh
- infrastructure/src/api/endpoints/delete-endpoints.ts
- middleware_api/lambda/endpoints/delete_endpoints.py
- middleware_api/lambda/endpoints/endpoint_event.py
> feat: improved delete endpoint

- aws_extension/mme_utils.py
- build_scripts/inference/serve.sh
- scripts/api.py
> feat: Improved sync

- docs/en/user-guide/training-guide.md
- docs/mkdocs.en.yml
- docs/mkdocs.zh.yml
- docs/zh/user-guide/training-guide.md
Add kohya training guide
- [ - ] This change requires a documentation update
> docs: add kohya training guide

- README.md
> feat: dev merge main

- aws_extension/sagemaker_ui_tab.py
- build_scripts/Dockerfile.inference.from_scratch
- build_scripts/build_and_push_local.sh
- build_scripts/build_inference_local.sh
- build_scripts/inference/serve.sh
- build_scripts/nginx_proxy.conf
- buildspec.yml
- middleware_api/lambda/endpoints/create_endpoint.py
> feat: improved docker file sync

- middleware_api/lambda/endpoints/list_endpoints.py
> fix: endpoint status

- aws_extension/sagemaker_ui.py
- aws_extension/sagemaker_ui_tab.py
> feat: support p4d

- aws_extension/sagemaker_ui_tab.py
- middleware_api/lambda/trainings/create_training_job.py
> fix: train status

- middleware_api/lambda/trainings/create_training_job.py
- support train model name check
> feat: Check name

- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/datasets/create-dataset.ts
- middleware_api/lambda/trainings/create_training_job.py
> feat: improved ui & train api

- middleware_api/lambda/trainings/delete_training_jobs.py
> fix: train job delete

- aws_extension/cloud_api_manager/api_manager.py
- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/datasets/get-dataset.ts
- infrastructure/src/api/inferences/get-inference-job.ts
- infrastructure/src/api/trainings/get-training-job.ts
- infrastructure/src/api/users/create-user.ts
- infrastructure/src/events/trainings-event.ts
- infrastructure/src/main.ts
- infrastructure/src/shared/inference.ts
- infrastructure/src/shared/resource-provider-on-event.ts
- infrastructure/src/shared/resource-waiter.ts
- infrastructure/src/shared/sns-topics.ts
- infrastructure/src/shared/train-deploy.ts
- middleware_api/lambda/checkpoints/update_checkpoint.py
- middleware_api/lambda/checkpoints/update_checkpoint_by_url.py
- middleware_api/lambda/common/util.py
- middleware_api/lambda/endpoints/endpoint_event.py
- middleware_api/lambda/inferences/test_inference_api.py
- middleware_api/lambda/trainings/create_training_job.py
- middleware_api/lambda/trainings/get_training_job.py
- middleware_api/lambda/trainings/list_training_jobs.py
- update_scripts/retained_sns
- workshop/ec2.yaml
- workshop/nginx_proxy.conf
> feat: improved cdk & webui

- infrastructure/src/api/comfy/query_execute.ts
- infrastructure/src/comfy/comfy-api-stack.ts
- infrastructure/src/main.ts
- infrastructure/src/shared/dataset.ts
> feat: Comfy cdk improved

- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/inferences/start-inference-job.ts
- infrastructure/src/shared/multi-users.ts
- infrastructure/src/shared/rest-api-gateway.ts
- middleware_api/lambda/inferences/create_inference_job.py
- middleware_api/lambda/inferences/start_inference_job.py
> feat: improved apis

- middleware_api/lambda/inferences/create_inference_job.py
- middleware_api/lambda/inferences/start_inference_job.py
> feat: updated from  dev

- build_scripts/inference/serve.sh
- middleware_api/lambda/endpoints/create_endpoint.py
> feat: Improved launch

- buildspec.yml
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/common/dockerImageTag.ts
- infrastructure/src/main.ts
- infrastructure/src/shared/resource-provider.ts
- middleware_api/lambda/endpoints/create_endpoint.py
> feat: Improved tag

- infrastructure/src/comfy/comfy-api-stack.ts
- infrastructure/src/common/dockerImageTag.ts
- infrastructure/src/endpoints/endpoint-stack.ts
- infrastructure/src/main.ts
- infrastructure/src/shared/resource-provider-on-event.ts
- infrastructure/src/shared/resource-provider.ts
- infrastructure/src/shared/sns-topics.ts
> improved launch logic

- build_scripts/inference/serve.sh
> feat: improved serve

- aws_extension/sagemaker_ui_tab.py
- build_scripts/inference/serve.sh
- infrastructure/src/shared/resource-provider-on-event.ts
- infrastructure/src/shared/resource-provider.ts
> feat: improved file_types

- aws_extension/cloud_api_manager/api_manager.py
- build_scripts/build_inference_local.sh
- build_scripts/comfy/serve.py
- build_scripts/inference/serve.sh
- infrastructure/src/api/endpoints/create-endpoint.ts
- middleware_api/lambda/endpoints/create_endpoint.py
- middleware_api/lambda/inferences/create_inference_job.py
> feat: Comfy docker

- infrastructure/src/api/comfy/excute.ts
- infrastructure/src/api/comfy/get_execute.ts
- infrastructure/src/api/comfy/get_prepare.ts
- infrastructure/src/api/comfy/get_sync_msg.ts
- infrastructure/src/api/comfy/prepare.ts
- infrastructure/src/api/comfy/query_execute.ts
- infrastructure/src/api/comfy/sync_msg.ts
- infrastructure/src/comfy/comfy-api-stack.ts
- middleware_api/lambda/comfy/execute.py
- middleware_api/lambda/comfy/execute_async_events.py
- middleware_api/lambda/comfy/get_execute.py
- middleware_api/lambda/comfy/get_prepare.py
- middleware_api/lambda/comfy/get_sync_msg.py
- middleware_api/lambda/comfy/prepare.py
- middleware_api/lambda/comfy/query_execute.py
- middleware_api/lambda/comfy/sync_msg.py
> improved api

- infrastructure/src/main.ts
- infrastructure/src/shared/const.ts
- infrastructure/src/shared/description.ts
> feat: Comfy api

- aws_extension/sagemaker_ui_tab.py
> feat: improved default dev

- middleware_api/lambda/libs/utils.py
> improved serve

- middleware_api/lambda/comfy/execute.py
> feat: improved api

- .gitignore
- build_scripts/inference/serve.sh
- infrastructure/src/api/comfy/excute.ts
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/comfy/comfy-api-stack.ts
- infrastructure/src/main.ts
- infrastructure/src/shared/resource-provider.ts
- infrastructure/src/shared/resource-waiter.ts
- middleware_api/lambda/comfy/execute.py
- middleware_api/lambda/endpoints/create_endpoint.py
> feat: Comfy api and endpoint call

- build_scripts/inference/serve.sh
- infrastructure/src/api/comfy/excute.ts
- infrastructure/src/shared/resource-provider-on-event.ts
- infrastructure/src/shared/sns-topics.ts
- middleware_api/lambda/comfy/execute.py
- middleware_api/lambda/endpoints/create_endpoint.py
- middleware_api/lambda/libs/comfy_data_types.py
> feat: update sns

- infrastructure/src/shared/resource-waiter-on-event.ts
> feat: improved waiters

- build_scripts/inference/serve.sh
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/api/endpoints/delete-endpoints.ts
- middleware_api/lambda/endpoints/create_endpoint.py
- middleware_api/lambda/endpoints/delete_endpoints.py
> feat: improved endpoint create

- build_scripts/comfy/comfy_local_proxy.py
- buildspec.yml
- workshop/comfy.yaml
> feat: Comfy api and ec2 template

- build_scripts/comfy/comfy_local_proxy.py
- workshop/comfy.yaml
> feat: improved comfy ec2 template

- build_scripts/comfy/comfy_local_proxy.py
- middleware_api/lambda/comfy/execute.py
- middleware_api/lambda/comfy/execute_async_events.py
- workshop/comfy.yaml
> feat: Improved local

- middleware_api/requirements.txt
- update lambda packages version
> feat: update lambda packages version

- build_scripts/inference/serve.sh
> feat: improved Serve logic

- build_scripts/Dockerfile.inference.cn.sd.from_scratch
> feat: support U2net human seg

- docs/en/developer-guide/api_inference_process.md
- docs/zh/developer-guide/api_inference_process.md
> feat: improved inference job

- docs/en/developer-guide/api/1.4.0.md
- docs/en/developer-guide/api/1.5.0.md
- docs/mkdocs.en.yml
- docs/mkdocs.zh.yml
- docs/oas-1.4.0.json
- docs/oas-1.5.0.json
- docs/zh/developer-guide/api/1.4.0.md
- docs/zh/developer-guide/api/1.5.0.md
> feat: improved api docs

- build_scripts/Dockerfile
- build_scripts/Dockerfile.from_scratch
- build_scripts/utils/cn_serve
- infrastructure/src/api/trainings/create-training-job.ts
- infrastructure/src/main.ts
- middleware_api/trainings/create_training_job.py
> feat: improved train parameters

- install.sh
> fix: download branch

- test/test_06_api_inference/test_14_txt2img_real_time.py
- test/test_06_api_inference/test_51_rembg_real_time.py
- test/test_06_api_inference/test_70_one_api_async.py
- test/test_06_api_inference/test_71_one_api_real_time.py
- test/test_07_api_inference_recreate/test_21_re_txt2img_real_time.py
- test/test_07_api_inference_recreate/test_51_re_rembg_real_time.py
- test/test_07_api_inference_recreate/test_70_re_one_api_async.py
- test/test_07_api_inference_recreate/test_71_re_one_api_real_time.py
- improved real-time inference time test
> feat: improved real-time inference time test

- test/buildspec_build.sh
- support update stack for test
> feat: support update stack for test

- infrastructure/src/shared/resource-provider-on-event.ts
- install.bat
- middleware_api/service/oas.py
- test/buildspec_build.sh
- test/buildspec_post_build.sh
- windows commitid for install
> fix: windows commitid for install

- middleware_api/service/oas.py
- test/buildspec_build.sh
- test/buildspec_post_build.sh
- test/test_06_api_inference/test_14_txt2img_real_time.py
- test/test_07_api_inference_recreate/test_21_re_txt2img_real_time.py
- improved some inference tests in some regions
> feat: improved some inference tests in some regions

- infrastructure/src/api/endpoints/delete-endpoints.ts
- infrastructure/src/events/endpoints-event.ts
- middleware_api/endpoints/create_endpoint.py
- middleware_api/endpoints/delete_endpoints.py
- middleware_api/endpoints/endpoint_event.py
- middleware_api/endpoints/list_endpoints.py
- middleware_api/inferences/create_inference_job.py
- middleware_api/inferences/start_inference_job.py
- middleware_api/libs/data_types.py
- middleware_api/libs/utils.py
- middleware_api/trainings/delete_training_jobs.py
- middleware_api/trainings/training_event.py
- test/test_02_api_base/test_07_endpoints.py
> feat: Improved ep delete

- test/test_06_api_inference/test_41_sd_xl_turbo.py
> feat: delete ep model in event

- docs/Environment-Preconfiguration.md
> feat: update ec2 yaml

- build_scripts/build_inference_local.sh
- build_scripts/install_sd.sh
> fix: serve sh

- build_scripts/Dockerfile.inference.build.sd.from_scratch
- build_scripts/inference/serve.sh
- build_scripts/trim_comfy.sh
- build_scripts/trim_sd.sh
- test/buildspec_build.sh
- test/buildspec_post_build.sh
> feat: Test

- build_scripts/build_and_export_files.sh
- build_scripts/inference/serve.sh
- use stable-diffusion-aws-extension-github-mainline as dir
> feat: use stable-diffusion-aws-extension-github-mainline as dir

- build_scripts/inference/serve.sh
- build_scripts/trim_comfy.sh
- build_scripts/trim_sd.sh
- test/config.py
- use trim scripts for endpoints
> feat: use trim scripts for endpoints

- infrastructure/src/shared/rest-api-gateway.ts
- javascript/txt2img-config.js
> fix: upload url get

- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/checkpoints/delete-checkpoints.ts
- infrastructure/src/api/checkpoints/update-chekpoint.ts
- infrastructure/src/api/comfy/delete_excutes.ts
- infrastructure/src/api/comfy/excute.ts
- infrastructure/src/api/comfy/prepare.ts
- infrastructure/src/api/comfy/sync_msg.ts
- infrastructure/src/api/datasets/create-dataset.ts
- infrastructure/src/api/datasets/delete-datasets.ts
- infrastructure/src/api/datasets/update-dataset.ts
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/api/endpoints/delete-endpoints.ts
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/api/inferences/delete-inference-jobs.ts
- infrastructure/src/api/roles/create-role.ts
- infrastructure/src/api/roles/delete-roles.ts
- infrastructure/src/api/trainings/create-training-job.ts
- infrastructure/src/api/trainings/delete-training-jobs.ts
- infrastructure/src/api/users/create-user.ts
- infrastructure/src/api/users/delete-users.ts
- infrastructure/src/shared/rest-api-gateway.ts
- infrastructure/src/shared/validator.ts
- use unique validator for update stack
> feat: use unique validator for update stack

- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/checkpoints/delete-checkpoints.ts
- infrastructure/src/api/checkpoints/update-chekpoint.ts
- infrastructure/src/api/comfy/delete_excutes.ts
- infrastructure/src/api/comfy/excute.ts
- infrastructure/src/api/comfy/prepare.ts
- infrastructure/src/api/comfy/sync_msg.ts
- infrastructure/src/api/datasets/create-dataset.ts
- infrastructure/src/api/datasets/delete-datasets.ts
- infrastructure/src/api/datasets/update-dataset.ts
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/api/endpoints/delete-endpoints.ts
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/api/inferences/delete-inference-jobs.ts
- infrastructure/src/api/roles/create-role.ts
- infrastructure/src/api/roles/delete-roles.ts
- infrastructure/src/api/trainings/create-training-job.ts
- infrastructure/src/api/trainings/delete-training-jobs.ts
- infrastructure/src/api/users/create-user.ts
- infrastructure/src/api/users/delete-users.ts
- infrastructure/src/shared/rest-api-gateway.ts
> feat: update validators

- docs/en/developer-guide/oas.md
- docs/ja/developer-guide/oas.md
- docs/zh/developer-guide/oas.md
> feat: use generate oas file

- docs/zh/developer-guide/api/esd-oas-v1.5.0.json
- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/checkpoints/delete-checkpoints.ts
- infrastructure/src/api/checkpoints/update-chekpoint.ts
- infrastructure/src/api/datasets/create-dataset.ts
- infrastructure/src/api/datasets/delete-datasets.ts
- infrastructure/src/api/datasets/update-dataset.ts
- infrastructure/src/api/endpoints/create-endpoint.ts
- infrastructure/src/api/endpoints/delete-endpoints.ts
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/api/inferences/delete-inference-jobs.ts
- infrastructure/src/api/roles/create-role.ts
- infrastructure/src/api/roles/delete-roles.ts
- infrastructure/src/api/trainings/create-training-job.ts
- infrastructure/src/api/trainings/delete-training-jobs.ts
- infrastructure/src/api/users/create-user.ts
- infrastructure/src/api/users/delete-users.ts
- middleware_api/service/oas.py
> feat: improved validator

- docs/zh/developer-guide/api/esd-oas-v1.5.0.json
- middleware_api/service/oas.py
> feat: OAS Docs

- build_scripts/comfy/restart.js
- build_scripts/comfy/restart.py
- build_scripts/install_comfy.sh
> feat: support restart comfy

- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/trainings/get-training-job.ts
- middleware_api/trainings/get_training_job.py
> feat: added logs for train

- aws_extension/cloud_api_manager/api.py
- aws_extension/sagemaker_ui_tab.py
- infrastructure/src/api/datasets/dataset-crop.ts
- test/test_12_client_check/bak_test_02_comfy_client_check.py
- test/test_12_client_check/test_01_webui_client_check.py
> feat: added crop ui

- aws_extension/sagemaker_ui_tab.py
- middleware_api/libs/data_types.py
- middleware_api/trainings/get_training_job.py
- middleware_api/trainings/training_event.py
> feat: supported loss logs list

- build_scripts/comfy/serve.py
- infrastructure/src/api/endpoints/create-endpoint.ts
> feat: supported metric record

- build_scripts/comfy/serve.py
- added put_metric_data for gpu
> feat: added put_metric_data for gpu

- build_scripts/comfy/serve.py
- test/test_10_local_only/test_03_comfy_mutli_gpus_tasks.py
> feat: rename GPU to InstanceGPU

- test/test_06_api_inference/test_08_comfy_inference_txt2img_async.py
- test/test_06_api_inference/test_09_comfy_inference_txt2img_real_time.py
- test/utils/helper.py
> feat: update tests

- infrastructure/src/main.ts
> feat: improved addDependency

- build_scripts/comfy/serve.py
> feat: Catch output

- build_scripts/comfy/serve.py
- test/test_10_local_only/test_02_comfy_mutil_gpus_tasks.py
- test/test_11_api_clean/test_07_clean_executes.py
> feat: improved process name

- build_scripts/inference/start.sh
- test/test_06_api_inference/test_01_sd_endpoint_check_async.py
- test/test_06_api_inference/test_02_sd_endpoint_check_real_time.py
- test/test_06_api_inference/test_03_comfy_endpoint_check_async.py
- test/test_06_api_inference/test_04_comfy_endpoint_check_real_time.py
- test/test_07_api_ep_recreate/test_02_re_sd_ep_recheck_async.py
- test/test_07_api_ep_recreate/test_03_re_sd_ep_recheck_real_time.py
- test/test_07_api_ep_recreate/test_04_re_comfy_ep_recheck_async.py
- test/test_07_api_ep_recreate/test_05_re_comfy_ep_recheck_real_time.py
- test/test_09_api_training/test_06_endpoint_check_async.py
- test/test_09_api_training/test_07_endpoint_check_real_time.py
- test/test_10_local_only/test_01_comfy_endpoint_create.py
- test/test_10_local_only/test_02_comfy_mutil_gpus_tasks.py
- test/utils/helper.py
> feat: Catch tests

- build_scripts/comfy/serve.py
> feat: improved set_prompt

- build_scripts/inference/metrics.py
- build_scripts/inference/start.sh
- middleware_api/comfy/execute.py
- middleware_api/comfy/execute_async_events.py
- middleware_api/common/util.py
- middleware_api/inferences/inference_async_events.py
- middleware_api/inferences/start_inference_job.py
> feat: added metric

- build_scripts/comfy/serve.py
- infrastructure/src/shared/log-sub-on-event.ts
> feat: added appendToS3Object

- build_scripts/comfy/serve.py
> feat: improved prompt_id for process

- build_scripts/comfy/serve.py
- infrastructure/src/shared/database.ts
- infrastructure/src/shared/log-sub-on-event.ts
- infrastructure/src/shared/resource-provider-on-event.ts
> feat: improved Log sub

- build_scripts/comfy/serve.py
- infrastructure/src/shared/log-sub.ts
> feat: log improved

- build_scripts/comfy/serve.py
> feat: use global var to save prompt id

- build_scripts/comfy/serve.py
- infrastructure/src/shared/log-sub-on-event.ts
> feat: improved prompt_id for log sub

- build_scripts/comfy/serve.py
> feat: improved print prompt_id

- build_scripts/comfy/serve.py
- middleware_api/endpoints/endpoint_event.py
> feat: rename pattern for log sub

- infrastructure/eslint.config.mjs
- infrastructure/package.json
- infrastructure/src/api/comfy/get_execute.ts
- infrastructure/src/api/comfy/get_execute_logs.ts
- infrastructure/src/comfy/comfy-api-stack.ts
- infrastructure/src/comfy/comfy-database.ts
- infrastructure/src/main.ts
- infrastructure/src/shared/database.ts
- middleware_api/comfy/get_execute.py
- middleware_api/comfy/get_execute_logs.py
- middleware_api/service/oas.py
> feat: added get execute logs api

- infrastructure/src/api/comfy/get_execute_logs.ts
- test/test_02_api_base/test_11_comfy.py
- test/test_10_local_only/test_04_comfy_single_gpu_tasks.py
- test/utils/helper.py
> feat: added get execute logs api tests

- infrastructure/src/api/comfy/get_execute_logs.ts
> feat: improved response model for log sub

- middleware_api/endpoints/delete_endpoints.py
- test/test_02_api_base/test_02_doc.py
- test/utils/api.py
> feat: improved endpoint delete

- middleware_api/comfy/execute_async_events.py
- middleware_api/common/util.py
> fix: status for execute

- middleware_api/common/util.py
- improved generate_presigned_url_for_keys
> feat: improved generate_presigned_url_for_keys

- infrastructure/src/events/endpoints-event.ts
- middleware_api/endpoints/endpoint_event.py
> feat: Improved del ep

- aws_extension/models.py
- build_scripts/comfy/serve.py
- middleware_api/comfy/execute_async_events.py
- middleware_api/inferences/inference_libs.py
- middleware_api/libs/comfy_data_types.py
- middleware_api/libs/data_types.py
- scripts/api.py
> feat: improved start time

- infrastructure/src/events/cloudwatch-event.ts
- infrastructure/src/shared/dashboard.ts
- middleware_api/endpoints/cloudwatch_event.py
- test/test_10_local_only/test_08_latency_tasks.py
> feat: improved ds

- infrastructure/src/shared/dashboard.ts
- middleware_api/endpoints/cloudwatch_event.py
> feat: improved ds height

- infrastructure/src/shared/dashboard.ts
> feat: improved delete ep

- middleware_api/common/util.py
- middleware_api/endpoints/delete_endpoints.py
> feat: fix ep delete

- aws_extension/sagemaker_ui_tab.py
- middleware_api/endpoints/create_endpoint.py
- scripts/api.py
> feat: improved loss log

- aws_extension/sagemaker_ui_tab.py
- build_scripts/install_sd.sh
- workshop/ami-gen.sh
- workshop/ec2.yaml
> feat: upgrade 1.9.3

- build_scripts/install_sd.sh
> feat: use 1.8

- test/test_02_api_base/test_07_endpoints.py
- test/test_11_api_clean/test_01_clean_endpoint.py
- test/utils/helper.py
> feat: added endpoint path check

- test/utils/helper.py
> feat: improved check_s3_directory

- aws_extension/models.py
- build_scripts/comfy/serve.py
- infrastructure/src/api/comfy/create_excute.ts
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/shared/schema.ts
- middleware_api/comfy/execute.py
- middleware_api/comfy/execute_async_events.py
- middleware_api/common/util.py
- middleware_api/inferences/create_inference_job.py
- middleware_api/inferences/inference_async_events.py
- middleware_api/inferences/start_inference_job.py
- middleware_api/libs/comfy_data_types.py
- middleware_api/libs/data_types.py
- scripts/api.py
- test/test_06_api_inference/test_08_comfy_inference_txt2img_async.py
- test/test_06_api_inference/test_10_txt2img_async_cn_1.py
- test/test_06_api_inference/test_11_txt2img_async_cn_2.py
- test/test_06_api_inference/test_12_txt2img_async_cn_3.py
- test/test_06_api_inference/test_13_txt2img_async.py
- test/test_06_api_inference/test_15_txt2img_reactor_async.py
- test/test_06_api_inference/test_20_esi_async.py
- test/test_06_api_inference/test_30_img2img_async.py
- test/test_06_api_inference/test_40_rembg_async.py
- test/test_06_api_inference/test_40_sla_txt2img_async.py
- test/test_06_api_inference/test_41_sd_xl_turbo.py
- test/test_06_api_inference/test_50_tps_real_time.py
- test/test_10_local_only/bak_test_05_sd_mutil_gpus_single_task.py
- test/test_10_local_only/bak_test_06_sd_mutil_gpus_tasks.py
- test/utils/helper.py
> feat: support Workflow metrics

- middleware_api/endpoints/cloudwatch_event.py
> feat: support workflow db

- middleware_api/comfy/execute.py
- middleware_api/common/util.py
- middleware_api/inferences/create_inference_job.py
> feat: improved wf name

- middleware_api/common/util.py
- middleware_api/endpoints/cloudwatch_event.py
> feat: improved workflow

- middleware_api/common/util.py
- test/test_06_api_inference/test_08_comfy_inference_txt2img_async.py
> feat: forbidden g6 temp

- build_scripts/comfy/serve.py
- build_scripts/inference/start.sh
- middleware_api/endpoints/create_endpoint.py
> feat: support env

- build_scripts/inference/start.sh
> fix: python venv permission

- middleware_api/endpoints/endpoint_event.py
> feat: improved docker

- .gitignore
- infrastructure/src/shared/rest-api-gateway.ts
- workshop/Dockerfile.comfy
- workshop/comfy.yaml
- workshop/ec2_start.sh
> feat: improved docker build

- workshop/Dockerfile.comfy
- workshop/comfy.yaml
- workshop/comfy_start.sh
- workshop/ec2_start.sh
> feat: improved cocker for ec2

- workshop/comfy.yaml
- workshop/comfy_start.sh
> feat: improved docker shell

- build_scripts/inference/start.sh
- enable pipefail for some functions
> feat: enable pipefail for some functions

- build_scripts/comfy/comfy_proxy.py
- build_scripts/inference/start.sh
- docker_image.sh
- docker_start.sh
- infrastructure/src/api/workflows/create-workflow.ts
- infrastructure/src/api/workflows/list-workflows.ts
- infrastructure/src/shared/schema.ts
- middleware_api/libs/data_types.py
- middleware_api/workflows/create_workflow.py
- test/test_02_api_base/test_12_workflows.py
- workshop/comfy_new.yaml
> feat: update docker start

- .viperlightignore
- aws_extension/sagemaker_ui.py
> feat: Sort lora models

- workshop/comfy_new.yaml
- workshop/ec2.yaml
> feat: added apt lock

- docker_start.sh
- workshop/comfy_new.yaml
> feat: Improved ec2

- build_scripts/comfy/comfy_proxy.py
> feat: improved release workflow

- build_scripts/comfy/comfy_proxy.py
- build_scripts/inference/start.sh
> feat: Async release improved

- .github/workflows/gh-pages.yml
- .viperlightignore
- docs/en/developer-guide/api/1.5.0.md
- docs/ja/developer-guide/api/1.5.0.md
- docs/zh/developer-guide/api/1.5.0.md
> fix: oas url

- docs/zh/deployment/deployment_comfyui.md
> feat: 1.6.0 fix doc address

- docs/zh/deployment/deployment_comfyui.md
> feat: fix doc address

- docker_start.sh
- workshop/comfy.yaml
- workshop/ec2.yaml
> feat: improved account id

- buildspec.yml
- infrastructure/src/main.ts
- workshop/comfy.yaml
- workshop/ec2.yaml
> feat: update ec2 files

- infrastructure/src/main.ts
> feat: improved tips for ec2

- .github/workflows/gh-pages.yml
> feat: improved oas

- .github/workflows/gh-pages.yml
> feat: fix oas file

- build_scripts/comfy/serve.py
> feat: check fix

- infrastructure/src/api/checkpoints/create-chekpoint.ts
- infrastructure/src/api/checkpoints/update-chekpoint.ts
- infrastructure/src/api/comfy/create_excute.ts
- infrastructure/src/api/comfy/delete_excutes.ts
- infrastructure/src/api/comfy/merge_execute.ts
- infrastructure/src/api/inferences/create-inference-job.ts
- infrastructure/src/api/inferences/start-inference-job.ts
- infrastructure/src/api/trainings/create-training-job.ts
- infrastructure/src/comfy/comfy-api-stack.ts
- infrastructure/src/events/cloudwatch-event.ts
- infrastructure/src/events/endpoints-event.ts
- infrastructure/src/shared/inference.ts
- infrastructure/src/shared/resource-provider.ts
- infrastructure/src/shared/resource-waiter.ts
> feat: improved lambda memory size

- build_scripts/comfy/comfy_proxy.py
- infrastructure/src/api/schemas/delete-schemas.ts
- infrastructure/src/api/schemas/update-schema.ts
- infrastructure/src/shared/schema.ts
- middleware_api/schemas/create_schema.py
- middleware_api/schemas/list_schemas.py
- middleware_api/schemas/update_schema.py
- test/test_02_api_base/test_13_schemas.py
- test/utils/api.py
> feat: support ec2 apis

- build_scripts/comfy/comfy_proxy.py
> feat: improved schema list

- middleware_api/inferences/inference_libs.py
> feat: Improved inference

- build_scripts/comfy/comfy_proxy.py
- build_scripts/inference/start.sh
- docker_start.sh
> feat: hidden mgr in slave

- docs/en/developer-guide/api_inference_process.md
- docs/ja/developer-guide/api_inference_process.md
- docs/zh/developer-guide/api_inference_process.md
> feat: improved infer process docs
